### ISSUE TITLE
CSS Styling doesn't show properly with big screenshots

### ISSUE THREAD

**Issue by advoiculescu** [concordion/concordion-storyboard-extension#4]
Hi. First of all, let me say thanks for making this awesome extension. It has proven to be really useful. 

One problem I've found is that the screenshot preview in the Storyboard doesn't handle big screenshots pretty well.

 In my case i use appium to take the screenshots and sometimes the device's resolution is quite big, so the screenshots taken are also big. When this happens, they css that handles the storyboard seems to show the preview (when you set the cursor on the images) off the screen.

Here i show a screenshot so you can see for yourself.  
![storyboard](https://cloud.githubusercontent.com/assets/16078599/12651234/0e515eae-c5e6-11e5-9365-a5739ce65373.jpg)

**Comment by andrew-sumner** [comment]
Thanks for letting me know and its great to hear that it's being used :-)

I'll have a look at this some time next week (away this weekend).  I've recently published a snapshot that supports the new Concordion 2.0 snapshot.  This has been a major rewrite and MAY have fixed your issue, however I will look into it and confirm this.

**Comment by andrew-sumner** [comment]
I haven't been able to duplicate the issue - I've tried both on the latest snapshot and the latest release version (0.3.3).

Could you check the version of the extension you're using and assuming it is the latest, could you zip up and example spec including all JavaScript and image files and email to me?

**Comment by advoiculescu** [comment]
The version i'm using is the following: 
`
		<dependency>
			<groupId>org.concordion</groupId>
			<artifactId>concordion-storyboard-extension</artifactId>
			<version>0.3.3</version>
		</dependency>
`
You don't seem to have your e-mail enabled on your profile, so i uploaded the zip to Google Drive.
Here you have the [link](https://drive.google.com/open?id=0BzVj7XzD9I7AQkJBUVo3NUFTTGs).

**Comment by andrew-sumner** [comment]
I've sorted out the issue and will have a new snapshot published in the next few days.  Unfortunately the snapshot will be no good to you unless you're also willing to upgrade to the Concordion 2.0 snapshot...

If the issue is really bothering you, you could replace storyboard.js with this code:

	function showScreenPopup(src) {
		var img = document.getElementById('StoryCardScreenshotPopup');
		img.src = src.src
		
		var scrollTop = Math.max(document.body.scrollTop, document.documentElement.scrollTop);
		var scrollLeft = Math.max(document.body.scrollLeft, document.documentElement.scrollLeft);
		var viewportWidth = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
		var viewportHeight = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;
		var scrollbarWidth = viewportWidth - document.body.offsetWidth;
		
		var srcRect = getSourceImageContainer(src).getBoundingClientRect();
		var imgRect = img.getBoundingClientRect();
		var naturalWidth = (img.naturalWidth || 0);
		var naturalHeight = (img.naturalHeight || 0);

		var above = srcRect.top > (viewportHeight - srcRect.top - srcRect.height);
		var posTop = 0;
		var posLeft = 0;
		
		if (above) {
			var height = Math.min(naturalHeight, srcRect.top - 10)
			posTop = scrollTop + srcRect.top - height;
			
			img.style.height = height + "px";
			img.style.width = 'auto';
			
			if (img.width > Math.min(naturalWidth, viewportWidth)) {
				img.style.height = 'auto';
				img.style.width = Math.min(naturalWidth, viewportWidth) + "px";
				
				posTop = scrollTop + srcRect.top - img.height;
			}
		} else {
			var height = Math.min(naturalHeight, viewportHeight - srcRect.top - srcRect.height - 10)
			posTop = scrollTop + srcRect.top + srcRect.height;
			
			img.style.height = height + "px";
			img.style.width = 'auto';
			
			if (img.width > Math.min(naturalWidth, viewportWidth)) {
				img.style.height = 'auto';
				img.style.width = Math.min(naturalWidth, viewportWidth) + "px";
			}
		}

		var posLeft = srcRect.left + scrollLeft + 1;
		   
		if (posLeft + img.width > scrollLeft + viewportWidth - scrollbarWidth) {
			posLeft = scrollLeft + viewportWidth - img.width - scrollbarWidth;
		}
		if (posLeft < scrollLeft) {
			posLeft = scrollLeft;
		}

		img.style.left = posLeft + "px";
		img.style.top = posTop + "px";
		img.style.visibility = 'visible';	
	}

	function getSourceImageContainer(src) {
		var node=src;
		
		while (node.offsetParent) {
			node=node.offsetParent;

			if (node.className.indexOf("scimgcontainer") >= 0) {
				return node;
			}
			/*
			var classList = node.classList || node.className;
			
			for (i = 0; i < classList.length; i++) { 
				if (classList[i] === "scimgcontainer") {
					return node;
				}
			}
			*/
		}
		
		return node;
	}

	function hideScreenPopup() {
		document.getElementById('StoryCardScreenshotPopup').style.visibility = 'hidden';
	}

	function showStoryboardSection(img, group, collapse, expand) {
		var display;
		
		if (getImageName(img.src) == getImageName(collapse)) {		
			img.src = expand;
			display = "none";
		} else {
			img.src = collapse;
			display = "inline-block";
		}
		
		var cards = document.getElementsByClassName(group);

		for (var i = 0; i < cards.length; i ++) {
			cards[i].style.display = display;
		}
	} 

	function getImageName(path) {
		var pos = path.lastIndexOf("/");

		if (pos > 0) {
			path = path.substring(pos + 1);
		}
		
		return path;	
	}

**Comment by advoiculescu** [comment]
Awesome! I'm closing this issue.

Keep up the good work!
